version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-claper}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DB:-claper}
    volumes:
      - claper-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB:-claper}", "-U", "${POSTGRES_USER:-claper}"]
      retries: 3
      timeout: 5s
    networks:
      - gkkckgoc4osg0ss44wgogk4c

  app:
    image: ghcr.io/claperco/claper:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - claper-uploads:/app/uploads

    # ↓↓↓ THIS IS THE CRITICAL BIT ↓↓↓
    ports:
      - "4000:4000"

    environment:
      - DATABASE_URL=${DATABASE_URL:?}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:?}
      - BASE_URL=${BASE_URL:?}
      - MAIL_FROM=${MAIL_FROM:-noreply@claper.co}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-Claper}
      - MAIL_TRANSPORT=${MAIL_TRANSPORT:-local}
      - PRESENTATION_STORAGE=${PRESENTATION_STORAGE:-local}
      - PRESENTATION_STORAGE_DIR=${PRESENTATION_STORAGE_DIR:-/app/uploads}

    healthcheck:
      test: "curl --fail http://localhost:4000 || exit 1"
      retries: 3
      start_period: 20s
      timeout: 5s

    labels:
      - caddy_0=https://claper.automate.business.aau.dk
      - caddy_0.handle_path=/*
      - caddy_0.handle_path.0_reverse_proxy={{upstreams}}
      - caddy_0.try_files={path} /index.html /index.php
      - caddy_0.encode=zstd gzip
      - caddy_0.header=-Server
      - caddy_ingress_network=gkkckgoc4osg0ss44wgogk4c
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-gkkckgoc4osg0ss44wgogk4c-app.entryPoints=http
      - traefik.http.routers.http-0-gkkckgoc4osg0ss44wgogk4c-app.middlewares=redirect-to-https
      - traefik.http.routers.http-0-gkkckgoc4osg0ss44wgogk4c-app.rule=Host(`claper.automate.business.aau.dk`) && PathPrefix(`/`)
      - traefik.http.routers.https-0-gkkckgoc4osg0ss44wgogk4c-app.entryPoints=https
      - traefik.http.routers.https-0-gkkckgoc4osg0ss44wgogk4c-app.middlewares=gzip
      - traefik.http.routers.https-0-gkkckgoc4osg0ss44wgogk4c-app.rule=Host(`claper.automate.business.aau.dk`) && PathPrefix(`/`)
      - traefik.http.routers.https-0-gkkckgoc4osg0ss44wgogk4c-app.tls=true
      - traefik.http.routers.https-0-gkkckgoc4osg0ss44wgogk4c-app.tls.certresolver=letsencrypt

    networks:
      - gkkckgoc4osg0ss44wgogk4c

volumes:
  claper-db:
    driver: local
  claper-uploads:
    driver: local

networks:
  gkkckgoc4osg0ss44wgogk4c:
    external: true
    name: gkkckgoc4osg0ss44wgogk4c